baseurl = "https://aino-spring.com/"
languageCode = "en-us"
theme = "nightfall"

[params]
author = "Aino Spring"
user = "info"
hostname = "aino-spring.com"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[menu]
    [[menu.header]]
        name = "posts"
        weight = 0
        url = "/posts"
    [[menu.header]]
        name = "about"
        weight = 0
        url = "/about"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/AinoSpring"
icon = "fa-brands fa-github fa-2xl"

[[params.social]]
key = 1
name = "instagram"
url = "https://instagram.com/aino.spring"
icon = "fa-brands fa-instagram fa-2xl"

[[params.social]]
key = 2
name = "email"
url = "mailto:info@aino-spring.com"
icon = "fa-solid fa-envelope fa-2xl"
